(IN-PACKAGE :LEM-USER)

(DEFINE-COLOR-THEME "challenger-deep" ()
  (:DISPLAY-BACKGROUND-MODE :DARK)
  (CURSOR :FOREGROUND "#565575" :BACKGROUND "#91DDFF")
  (REGION :BACKGROUND "#1E1C31")
  (SYNTAX-WARNING-ATTRIBUTE :FOREGROUND "#FF0000" :BOLD-P T)
  (SYNTAX-COMMENT-ATTRIBUTE :FOREGROUND "#767676")
  (SYNTAX-KEYWORD-ATTRIBUTE :FOREGROUND "#FF8080")
  (SYNTAX-CONSTANT-ATTRIBUTE :FOREGROUND "#FFE9AA")
  (SYNTAX-FUNCTION-NAME-ATTRIBUTE :FOREGROUND "#C991E1")
  (SYNTAX-TYPE-ATTRIBUTE :FOREGROUND "#91DDFF")
  (SYNTAX-BUILTIN-ATTRIBUTE :FOREGROUND "#D7AFFF")
  (LEM.SHOW-PAREN:SHOWPAREN-ATTRIBUTE :FOREGROUND "#100E23"
                                      :BACKGROUND "#C991E1")
  (LEM.LINE-NUMBERS:LINE-NUMBERS-ATTRIBUTE :FOREGROUND "#565575"
                                           :BACKGROUND NIL))

(LOAD-THEME "challenger-deep")

(DEFINE-KEY *GLOBAL-KEYMAP* "C-_" 'LEM:UNDO)
(DEFINE-KEY *GLOBAL-KEYMAP* "C-\\" 'LEM:REDO)

(SETF *SCROLL-RECENTER-P* NIL)
