(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(auth-source-save-behavior nil)
 '(auto-save-file-name-transforms '((".*" "~/.emacs.d/autosave" t)))
 '(backup-directory-alist '((".*" . "~/.emacs.d/backup")))
 '(blink-cursor-mode t)
 '(browse-url-browser-function 'xwidget-webkit-browse-url)
 '(browse-url-secondary-browser-function 'browse-url-xdg-open)
 '(column-number-mode t)
 '(connection-local-criteria-alist
   '(((:application eshell)
      eshell-connection-default-profile)
     ((:application tramp)
      tramp-connection-local-default-system-profile tramp-connection-local-default-shell-profile)))
 '(connection-local-profile-alist
   '((eshell-connection-default-profile
      (eshell-path-env-list))
     (tramp-connection-local-darwin-ps-profile
      (tramp-process-attributes-ps-args "-acxww" "-o" "pid,uid,user,gid,comm=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" "-o" "state=abcde" "-o" "ppid,pgid,sess,tty,tpgid,minflt,majflt,time,pri,nice,vsz,rss,etime,pcpu,pmem,args")
      (tramp-process-attributes-ps-format
       (pid . number)
       (euid . number)
       (user . string)
       (egid . number)
       (comm . 52)
       (state . 5)
       (ppid . number)
       (pgrp . number)
       (sess . number)
       (ttname . string)
       (tpgid . number)
       (minflt . number)
       (majflt . number)
       (time . tramp-ps-time)
       (pri . number)
       (nice . number)
       (vsize . number)
       (rss . number)
       (etime . tramp-ps-time)
       (pcpu . number)
       (pmem . number)
       (args)))
     (tramp-connection-local-busybox-ps-profile
      (tramp-process-attributes-ps-args "-o" "pid,user,group,comm=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" "-o" "stat=abcde" "-o" "ppid,pgid,tty,time,nice,etime,args")
      (tramp-process-attributes-ps-format
       (pid . number)
       (user . string)
       (group . string)
       (comm . 52)
       (state . 5)
       (ppid . number)
       (pgrp . number)
       (ttname . string)
       (time . tramp-ps-time)
       (nice . number)
       (etime . tramp-ps-time)
       (args)))
     (tramp-connection-local-bsd-ps-profile
      (tramp-process-attributes-ps-args "-acxww" "-o" "pid,euid,user,egid,egroup,comm=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" "-o" "state,ppid,pgid,sid,tty,tpgid,minflt,majflt,time,pri,nice,vsz,rss,etimes,pcpu,pmem,args")
      (tramp-process-attributes-ps-format
       (pid . number)
       (euid . number)
       (user . string)
       (egid . number)
       (group . string)
       (comm . 52)
       (state . string)
       (ppid . number)
       (pgrp . number)
       (sess . number)
       (ttname . string)
       (tpgid . number)
       (minflt . number)
       (majflt . number)
       (time . tramp-ps-time)
       (pri . number)
       (nice . number)
       (vsize . number)
       (rss . number)
       (etime . number)
       (pcpu . number)
       (pmem . number)
       (args)))
     (tramp-connection-local-default-shell-profile
      (shell-file-name . "/bin/sh")
      (shell-command-switch . "-c"))
     (tramp-connection-local-default-system-profile
      (path-separator . ":")
      (null-device . "/dev/null"))))
 '(current-language-environment "UTF-8")
 '(custom-safe-themes
   '("512ce140ea9c1521ccaceaa0e73e2487e2d3826cc9d287275550b47c04072bc4" "2078837f21ac3b0cc84167306fa1058e3199bbd12b6d5b56e3777a4125ff6851" "8d5f22f7dfd3b2e4fc2f2da46ee71065a9474d0ac726b98f647bc3c7e39f2819" "ec2c86933a6e0b96f68f71d4b39ebdd67b43b0b32091b7689acb9acdc2a3e03b" default))
 '(default-input-method "chinese-array30")
 '(dired-dwim-target 'dired-dwim-target-next)
 '(display-line-numbers 'relative)
 '(display-line-numbers-current-absolute nil)
 '(display-line-numbers-type 'relative)
 '(display-line-numbers-width-start nil)
 '(display-time-24hr-format t)
 '(display-time-day-and-date t)
 '(display-time-default-load-average nil)
 '(erc-nick "CToID")
 '(fill-column 80)
 '(font-lock-maximum-decoration
   '((racket-mode . 0)
     (emacs-lisp-mode . 0)
     (list-data-mode . 0)
     (lisp-mode . 0)
     (t . t)))
 '(frame-resize-pixelwise t)
 '(fringe-mode '(0) nil (fringe))
 '(garbage-collection-messages t)
 '(global-display-line-numbers-mode t)
 '(gnus-init-file "~/dotfiles/.emacs.d/.gnus")
 '(ibuffer-saved-filter-groups
   '(("customized"
      ("Dired"
       (mode . dired-mode))
      ("Magit"
       (name . "magit[-:].+"))
      ("Emacs"
       (name . "*[^*]+*")))))
 '(ido-default-buffer-method 'selected-window)
 '(ido-default-file-method 'selected-window)
 '(ido-enable-flex-matching t)
 '(ido-everywhere t)
 '(ignored-local-variable-values '((變數名 . 值)))
 '(image-animate-loop t)
 '(indent-tabs-mode nil)
 '(inhibit-startup-screen t)
 '(js-chain-indent t)
 '(line-number-display-limit-width most-positive-fixnum)
 '(line-spacing nil)
 '(major-mode-remap-alist '((perl-mode . cperl-mode)))
 '(menu-bar-mode nil)
 '(org-agenda-files '("~/Documents/agenda.org"))
 '(org-capture-templates
   '(("n" "General notes" entry
      (file+olp+datetree "")
      "* %?\12%U by %n" :empty-lines-after 1)))
 '(org-edit-src-content-indentation 0)
 '(org-export-preserve-breaks t)
 '(org-export-with-sub-superscripts '{})
 '(org-id-link-to-org-use-id 'create-if-interactive-and-no-custom-id)
 '(org-image-actual-width 500)
 '(org-log-done 'note)
 '(org-modules
   '(ol-bbdb ol-bibtex ol-docview ol-doi ol-eww ol-gnus ol-info ol-irc ol-mhe ol-rmail org-tempo ol-w3m))
 '(org-roam-dailies-directory "journal/")
 '(org-roam-directory "~/Documents/org-roam/")
 '(org-src-preserve-indentation t)
 '(org-src-tab-acts-natively t)
 '(org-todo-keywords '((sequence "TODO(t)" "DONE(d)")))
 '(org-use-sub-superscripts '{})
 '(package-selected-packages
   '(vterm treesit-auto vterm-toggle elfeed ladger-mode marginalia orderless vertico org-roam screenshot markdown-mode magit emms 0blayout keycast doom-themes
           #("eshell-prompt-extras" 0 20
             (escaped t))
           "eshell-prompt-extras" all-the-icons-dired use-package browse-kill-ring arduino-mode xclip yaml-mode visual-fill-column visual-fill-column-mode visual-line-mode highlight-indent-guides org-present org-present-mode toc-org sudo-edit neotree which-key ##))
 '(read-buffer-completion-ignore-case t)
 '(read-file-name-completion-ignore-case t)
 '(require-final-newline t)
 '(safe-local-variable-values
   '((display-line-numbers . visual)
     (display-line-numbers-type . visual)))
 '(save-place-mode t)
 '(scalable-fonts-allowed t)
 '(screenshot-border-width 0)
 '(screenshot-line-numbers-p nil)
 '(screenshot-radius 0)
 '(screenshot-relative-line-numbers-p nil)
 '(screenshot-shadow-intensity 0)
 '(screenshot-shadow-radius 0)
 '(scroll-bar-mode nil)
 '(scroll-conservatively 101)
 '(scroll-error-top-bottom t)
 '(scroll-preserve-screen-position 1)
 '(select-enable-clipboard nil)
 '(sh-basic-offset 2)
 '(show-paren-mode t)
 '(size-indication-mode t)
 '(tool-bar-mode nil)
 '(warning-suppress-types '((comp) (comp)))
 '(x-select-enable-clipboard-manager nil))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
